### ISSUE TITLE
想问一下具体使用方法

### ISSUE THREAD

**Issue by carr0t2** [Icemap/AMapAPI#1]
jar运行后能打开网页，控制台试了一下可以使用，但是不知用java多线程的办法

**Comment by Icemap** [comment]
是需要直接使用Java调用吗？
我的预想中这个项目是独立运行，与其他的服务是以接口进行交互的，接口文档在[这里](https://github.com/Icemap/AMapAPI#%E6%94%AF%E6%8C%81%E6%8E%A5%E5%8F%A3)。
如果需要以代码方式调用，可以使用Controller中调用的Service。
